#!/bin/bash


tmux
tmux send-key "rm routerLog" enter
#tmux selectp -t 0
tmux send-keys "python2 -u tyrouter.py test1 A | ts | tee -a -i routerLog" enter
tmux splitw -h -p 50
tmux send-keys "python2 -u tyrouter.py test1 B | ts | tee -a -i routerLog" enter
tmux splitw -v -p 50
tmux send-keys "python2 -u tyrouter.py test1 C | ts | tee -a -i routerLog" enter
tmux splitw -h -p 50
tmux send-keys "python2 -u tyrouter.py test1 D | ts | tee -a -i routerLog" enter
tmux selectp -t 0
tmux splitw -v -p 50
tmux send-keys "python2 -u tyrouter.py test1 E | ts | tee -a -i routerLog" enter
tmux splitw -v -p 50




