#!/bin/bash


tmux
#tmux selectp -t 0
tmux send-key "rm routerLog" enter
tmux send-keys "python2 -u tyrouter.py test4 A | ts | tee -a -i routerLog" enter
tmux splitw -h -p 50
tmux send-keys "python2 -u tyrouter.py test4 B | ts | tee -a -i routerLog" enter
tmux splitw -v -p 50
tmux send-keys "python2 -u tyrouter.py test4 C | ts | tee -a -i routerLog" enter
tmux splitw -h -p 50
tmux send-keys "python2 -u tyrouter.py test4 D | ts | tee -a -i routerLog" enter
tmux selectp -t 0
tmux splitw -v -p 80
tmux send-keys "python2 -u tyrouter.py test4 E | ts | tee -a -i routerLog" enter
tmux splitw -v -p 50
tmux send-keys "python2 -u tyrouter.py test4 F | ts | tee -a -i routerLog" enter
tmux splitw -v -p 50
tmux send-keys "python2 -u tyrouter.py test4 G | ts | tee -a -i routerLog" enter

tmux splitw -v -p 50
tmux send-keys "python2 -u tyrouter.py test4 H | ts | tee -a -i routerLog" enter

